#!/bin/sh

LIBDIR="/usr/lib/jshlint"
LIB="lint.js"
LIBPATH="$LIBDIR/$LIB"

FILE="$@"
if [ -z "$FILE" ]; then
  echo File required >&2
  exit 1
fi

FILE="$(realpath "$FILE")"
if [ ! -f "$FILE" ]; then
  echo File not found: "$FILE" >&2
  exit 1
fi

if [ ! -f "$LIB" ]; then
  if [ ! -f "$LIBPATH" ]; then
    echo lint.js not found >&2
    exit 1
  fi

  LIB="$LIBPATH"

  # this is hacky, but so is the js interpreter
  FILE="../../../$FILE"
fi

js "$LIB" "$FILE"
