#!/bin/sh

LIBDIR="/usr/lib/jshlint"
LIB="lint.js"
LIBPATH="$LIBDIR/$LIB"

if [ ! -f "$LIB" ]; then
  if [ ! -f "$LIBPATH" ]; then
    echo lint.js not found
    exit 1
  else
    LIB="$LIBPATH"
  fi
fi

if [ -f "$@" ]; then
  js "$LIB" "$@"
else
  echo File not found: "$@"
  exit 1
fi
