#!/bin/sh

LIBDIR="/usr/lib/jshlint"
LIB="lint.js"
LIBPATH="$LIBDIR/$LIB"

FILE="$1"
if [ -z "$FILE" ]; then
  echo File required
  exit 1
fi

if [ ! -f "$LIB" ]; then
  if [ ! -f "$LIBPATH" ]; then
    echo lint.js not found
    exit 1
  else
    LIB="$LIBPATH"
  fi
fi

if [ -f "$FILE" ]; then
  js "$LIB" "`realpath $FILE`"
else
  echo File not found: "$FILE"
  exit 1
fi
